"""visit module

Revision ID: 04fddf379ba9
Revises: 55476d029d83
Create Date: 2026-09-07 00:46:38.385365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fddf379ba9'
down_revision: Union[str, Sequence[str], None] = '55476d029d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'created_by')
    # ### end Alembic commands ###
