"""alter patient table

Revision ID: 6aac33a964c0
Revises: ca07a6491f1a
Create Date: 2026-09-03 12:07:22.628865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aac33a964c0'
down_revision: Union[str, Sequence[str], None] = 'ca07a6491f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'patients', 'media', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    # ### end Alembic commands ###
