"""pathogen and antimicrobial

Revision ID: dc6f7656a974
Revises: ef0c6f97521f
Create Date: 2026-09-07 13:31:09.271863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6f7656a974'
down_revision: Union[str, Sequence[str], None] = 'ef0c6f97521f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_visits', sa.Column('symptoms', sa.Text(), nullable=True))
    op.drop_column('clinical_visits', 'chief_complaint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_visits', sa.Column('chief_complaint', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('clinical_visits', 'symptoms')
    # ### end Alembic commands ###
