"""pathogen and antimicrobial

Revision ID: ef0c6f97521f
Revises: 04fddf379ba9
Create Date: 2026-09-07 11:22:59.031189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0c6f97521f'
down_revision: Union[str, Sequence[str], None] = '04fddf379ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antimicrobials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('generic_name', sa.String(length=150), nullable=True),
    sa.Column('drug_class', sa.Enum('PENICILLIN', 'CEPHALOSPORIN', 'FLUOROQUINOLONE', 'AMINOGLYCOSIDE', 'MACROLIDE', 'TETRACYCLINE', 'CARBAPENEM', 'SULFONAMIDE', 'GLYCOPEPTIDE', 'OTHER', name='antimicrobialclass'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('route_of_administration', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_antimicrobials_id'), 'antimicrobials', ['id'], unique=False)
    op.create_index(op.f('ix_antimicrobials_name'), 'antimicrobials', ['name'], unique=True)
    op.create_table('pathogens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('family', sa.Enum('GRAM_POSITIVE', 'GRAM_NEGATIVE', 'FUNGAL', 'VIRAL', 'OTHER', name='pathogenfamily'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('common_resistance_profile', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pathogens_id'), 'pathogens', ['id'], unique=False)
    op.create_index(op.f('ix_pathogens_name'), 'pathogens', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pathogens_name'), table_name='pathogens')
    op.drop_index(op.f('ix_pathogens_id'), table_name='pathogens')
    op.drop_table('pathogens')
    op.drop_index(op.f('ix_antimicrobials_name'), table_name='antimicrobials')
    op.drop_index(op.f('ix_antimicrobials_id'), table_name='antimicrobials')
    op.drop_table('antimicrobials')
    # ### end Alembic commands ###
